### ISSUE TITLE
from selenium to selene

### ISSUE THREAD

**Issue by sugizo** [yashaka/selene#287] opened 2021-02-27 18:29 UTC
**try**
```
config.browser_name = 'chrome'
browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
browser.element('#auth_user_email').set_value(new_valid_email)
browser.element('#auth_user_password').set_value(new_password)
browser.element('//*[@id="submit_record__row"]/div/input').click()
if "Log In" in browser:
    print("Log In Failed")
else:
    print("Log In Success")
browser.quit()
```

**result**
just open the page, no words typed, submit element not clicked and no print result 'success' or 'failed'

**question**
how to achieve it using selene ?

**e.g. in selenium**
```
browser = webdriver.Chrome()
browser.get(('http://stifix.pythonanywhere.com/welcome/default/user/login') )
browser.find_element_by_id('auth_user_email').send_keys(new_valid_email)
browser.find_element_by_id('auth_user_password').send_keys(new_password)
browser.find_element_by_xpath('//*[@id="submit_record__row"]/div/input').click()
if "Log In" in browser.page_source:
    print("Log In Failed")
else:
    print("Log In Success")
browser.quit()
```

**opinion**
syntax is quite different from selene with selenium and splinter
in selenium and splinter is quite same, but i appreciate variety, that's why want to learn how it works on selene

**suggestion**
perhaps can activate github discussion so the question like this can goes there

thx

**Comment by aleksandr-kotlyar** [comment] 2021-03-08 22:08
Hi, @sugizo. Thank you for the question. 

First of all:
1. What version of selene do you use?
2. What the stacktrace you get after this code executed?
3. What imports did you use for your code?

> 
> ```python
> config.browser_name = 'chrome'
> browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
> browser.element('#auth_user_email').set_value(new_valid_email)
> browser.element('#auth_user_password').set_value(new_password)
> browser.element('//*[@id="submit_record__row"]/div/input').click()
> if "Log In" in browser:
>     print("Log In Failed")
> else:
>     print("Log In Success")
> browser.quit()
> ```
> 

I copied your code, imported 'config' and 'browser':
```python
from selene.support.shared import config, browser

def test_gh_287_selene():
    config.browser_name = 'chrome'
    browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
    browser.element('#auth_user_email').set_value("abc")
    browser.element('#auth_user_password').set_value("cde")
    browser.element('//*[@id="submit_record__row"]/div/input').click()
    if "Log In" in browser:
        print("Log In Failed")
    else:
        print("Log In Success")
    browser.quit()
```
And i see that the error you may get on the row with `if "Log In" in browser`.
```bash
tests/test_triage.py:3 (test_gh_287_selene)
def test_gh_287_selene():
        config.browser_name = 'chrome'
        browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
        browser.element('#auth_user_email').set_value("abc")
        browser.element('#auth_user_password').set_value("cde")
        browser.element('//*[@id="submit_record__row"]/div/input').click()
>       if "Log In" in browser:
E       TypeError: argument of type 'SharedBrowser' is not iterable
```
That's not how selene works. If you want to check if the string is in browser title - you should get title from browser driver `browser.driver.title`. So when I fixed this step:

```python
from selene.support.shared import config, browser

def test_gh_287_selene():
    config.browser_name = 'chrome'
    browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
    browser.element('#auth_user_email').set_value("abc")
    browser.element('#auth_user_password').set_value("cde")
    browser.element('//*[@id="submit_record__row"]/div/input').click()
    if "Log In" in browser.driver.title:  # <---- add '.driver.title' here
        print("Log In Failed")
    else:
        print("Log In Success")
    browser.quit()
```
and test passed. I used `selene==2.0.0a34`.
<img width="1163" alt="Снимок экрана 2021-03-09 в 1 06 49" src="https://user-images.githubusercontent.com/17043964/110388215-c9ca3a00-8073-11eb-9ced-04693d491436.png">

**Comment by sugizo** [comment] 2021-03-08 23:11
1. What version of selene do you use?
1.0.2

2. What the stacktrace have you got after executed the code above?
no stacktrace occured
the result (not expected) is just open the url, no value typed on form field, no submit button clicked and also not quit browser

3. What imports did you use for your code?
```
from selene import config, browser
config.browser_name = 'chrome'
browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
browser.element('#auth_user_email').set_value("abc")
browser.element('#auth_user_password').set_value("cde")
browser.element('//*[@id="submit_record__row"]/div/input').click()
if "Log In" in browser.driver.title:
    print("Log In Failed")
else:
    print("Log In Success")
browser.quit()
```

**p.s.**
tested on :
- Python 3.8.8
- miniconda
- jupyter notebook

**Comment by aleksandr-kotlyar** [comment] 2021-03-09 08:18
@sugizo I tested selene==1.0.2 with your imports.

I got an error:
```python
        from selene import config, browser
        config.browser_name = 'chrome'
        browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
        browser.element('#auth_user_email').set_value("abc")
        browser.element('#auth_user_password').set_value("cde")
        browser.element('//*[@id="submit_record__row"]/div/input').click()
>       if "Log In" in browser.title:
E       TypeError: argument of type 'function' is not iterable

test_triage.py:8: TypeError
```
Because 'browser' in selene 1.0.2 doesn't have 'title' property, but it has a function `title()`, so if you use it, your script will be fixed like this:

```python
from selene import config, browser

config.browser_name = 'chrome'
browser.open_url('http://stifix.pythonanywhere.com/welcome/default/user/login')
browser.element('#auth_user_email').set_value("abc")
browser.element('#auth_user_password').set_value("cde")
browser.element('//*[@id="submit_record__row"]/div/input').click()
if "Log In" in browser.title():  # <--- added '()' after title
    print("Log In Failed")
else:
    print("Log In Success")
browser.quit()
```
![image](https://user-images.githubusercontent.com/17043964/110439489-95cd3400-80c8-11eb-8ec5-44268a59ee5a.png)

But I tested it on pure python with virtualenv, not conda or miniconda and not in jupiter notebook. If you will still have a problem - let us know and we will try to find more time to explore your setup to find out where is the problem

**Comment by yashaka** [comment] 2021-03-09 08:55
@sugizo 

> opinion
> syntax is quite different from selene with selenium and splinter
> in selenium and splinter is quite same, but i appreciate variety, that's why want to learn how it works on selene

Regarding different from selenium webdriver syntax. This is by intent/by design –  in order to provide the API of higher level of abstraction and focused on:
* how user works with elements
* how tester tests web pages

Selenium WeDriver is a low level tool that provides low level API in all its power in order to control browser in all possible scenarios. 
But in tests we usually need to interact with an App as a real user, with some "testing context" nuances. Thinking this way, it becomes pretty natural to provide a different more high level API in any selenium based wrapper that focus on testing and real user simulation.

**Comment by yashaka** [comment] 2021-03-09 10:24
@sugizo, it also might be some incompatibility issue between selene and jupyter. We will try to reproduce the issue with similar environment to yours.

> tested on :
>    Python 3.8.8
>    miniconda
>    jupyter notebook

Can you also share your ideas and goals regarding the context you are trying to use Selene in. I mean, why do you need to use selenium, or splinter or selene with Jupyter Notebooks – a tooling for scientific data analysis?

Selenium/Selene/Splinter are tools for mainly functional web ui testing. And usually we use them in a combination with other tools, like simply raw python + pytest + sele* and some tooling for project/env setup, like pyenv, pipenv, poetry, etc.

> in selenium to splinter vice versa, it just small step learning curve (different syntax is few, yet works well with so little effort)

this statement, is not fully true without specifying the context. Selenium is much bigger than features used in your original script, and if you count the common use cases of selenium webdriver / splinter in context of test automation, you would find the the learning curve is much bigger than you originally thought. Moreover some areas commonly used in test automation, are completely not addressed in the original Selenium WebDriver. 

I am telling all this not to blame others and highlight Selene. Selene has its cons. And especially right now, because of upcoming 2.0 release, that chages the API with some breaking changes, it's confusing to get Selene up & running with correct version in an easy intuitive way, without understanding some nuances from Documentation. But if you read Selene's Readme and follow the official recommendations on how to setup everything, you would success much faster. We will fix all this soon once 2.0 is released. Right now, at least I recommend you to use 2.0 alpha versions instead of 1.0.2. 

Yet, I really appreciate that you find these issues with Jupyter. They might reveal some issues in Selene that would be good to fix. Thank you for this!

**Comment by yashaka** [comment] 2021-03-10 07:16
> Try it with Jupyter Notebooks is some like testing the code before goes to production (create python script)

You are using a tool completely not for web ui testing. 
Once you have python in the system, Install something like PyCharm Community Edition, create a project with automatic env creation, add selene via UI from project interpreter settings, open a python file, put your code there and you are ready to go. If needed go into debug mode, and play with selene in-live. As simple as opening python file in editor with python installed. Yet, ready to extend to full power by adding pytest, etc.

Yet, we will see into issues with Jupyter integration. But for now, I recommend a more natural way of working with selenium-based tools. 

> in selenium
> assert "Log In" in browser.page_source
> and
> in splinter
> assert browser.is_text_present("Log In")
> in selene you must check it from another perspective which is check browser title

Heh... No, you must not check browser title:) You can check test on the page, you can do:

example 1
```
browser.element(by.partial_text('Log in')).should(be.visible)
```
or you can do
example 2
```
browser.element('body').should(have.text('Log in'))
```

Example 2 is doing the same thing that splinter does in `assert browser.is_text_present("Log In")`. And... both splinter and selene are doing the completely different thing than this selenium code:

```
assert "Log In" in browser.page_source
```

This selenium code checks text in page_source. Text in page_source and text visible on the page are completely different things. If text is hidden from the page, checking code in page_source will still pass. In fact you wrote completely different code for selenium and splinter and even did not understood it. 

Moreover, if site will load a bit longer, and text will appear with a delay, the selenium code will not give you what you would want in real test. This is also a point to clarify in all three – selenium, splinter, selene – they all will be different. And selene here would be more natural, it will give you the behaviour of a real user. 

You see what i mean? You try to write code by following some "selenium-based" template, trying to find similarities in syntax and thinking about this as a "good aproach" to move from selenium to another... But this does not work. Selenium Webdriver is a very complicated thing, you can't just try to find some similarities and build your scripts based on that. With splinter - same thing. You have to understand what you are writing, not just copy&pasting examples and trying to translate by "pseudo-similarities" to another framework. Moreover, it's also about writing stable code, not prone to false failures. And here we again have completely different picture in Selenium and Splinter. 

One more argument. Imagine you know how to drive a car with manual transmission. What happens if you will start to apply its principles/patterns to the car with an automatic transmission? 

With selenium it is much more complex. Selenium Webdriver patterns and Splinter or Selene patterns are different. You have to learn a different approach to write tests. Moreover, this approach has to be different, because selenium's approach is not suitable for testing web apps. And this is a big problem of Splinter too, that does not understand this and try to replicate "patterns of driving a car with a manual transmission when driving a car with automatic transmission". What you saw as an advantage of Splinter is also a disadvantage in many other areas. 

Splinter sometimes is trying to replicate the manual transmission, which is almost useless in real cities with traffic jams. Selene replicates automatic transmission the way how users are using it – that's why it is different, this is the main strong point of it;) But again, when understanding how selenium and splinter work under the hood and knowing principles of writing stable efficient tests – it will be much easier to see the proper similarities;)

And remember, it's not about "syntax", it's about principles of writing stable and efficient tests. This is the key. If you know them, if you understand how Selene API works – it's not a big deal, read the Readme that describes its simplicity, – then you can progress much faster. Or go your way, but then Selene might be not for you.

**Comment by yashaka** [comment] 2021-03-10 09:06
@sugizo 
I recorded a few videos in the context of our discussion. I hope they might clarify some things about Selene. 
[From Selenium to Selene – Part 1 – Intro To Core API Ideas](https://www.loom.com/share/b129c94c458147f28a2a805e047bc973)
[From Selenium to Selene – Part 2 – Demo](https://www.loom.com/share/9d2daf9ea7de41e1b8e18712f8bdcfa5)

**Comment by sugizo** [comment] 2021-03-10 14:56
thx for further explanation on video
tried latest recommended version
**env**
```
os : Darwin
conda : 4.9.2 (miniconda)
Python : 3.8.8
selene : 2.0.0a34
jupyter core : 4.7.0
jupyter-notebook : 6.2.0
```

**tested on jupyter**
```
pip install -U selene --pre
from selene.support.shared import browser
browser.config.browser_name = 'chrome'
browser.open('https://stifix.pythonanywhere.com/welcome/default/user/login')
browser.element('#auth_user_email').should(be.blank).type('abc')
browser.element('#auth_user_password').should(be.blank).type('cde')
browser.element('#//*[@id="submit_record__row"]/div/input').click()
browser.element('body').should(have.text('Log in') )
browser.quit()
```

**result**
- only browser open with url https://stifix.pythonanywhere.com/welcome/default/user/login
- no type on both #auth_user_email and #auth_user_password
- no click submit button
- not quit browser

**tested on python : selene.py**
```
cat << EOF > selene.py
from selene.support.shared import browser
browser.config.browser_name = 'chrome'
browser.open('https://stifix.pythonanywhere.com/welcome/default/user/login')
browser.element('#auth_user_email').should(be.blank).type('abc')
browser.element('#auth_user_password').should(be.blank).type('cde')
browser.element('#//*[@id="submit_record__row"]/div/input').click()
browser.element('body').should(have.text('Log in') )
browser.quit()
EOF
python selene.py
```

**result**
```
Traceback (most recent call last):
  File "selene.py", line 1, in <module>
    from selene.support.shared import browser
  File "/Users/sugizo/Downloads/jupyter/selene.py", line 1, in <module>
    from selene.support.shared import browser
ModuleNotFoundError: No module named 'selene.support'; 'selene' is not a package
```

so tried python from terminal
```
$ python
Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selene.support.shared import browser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sugizo/Downloads/jupyter/selene.py", line 1, in <module>
    from selene.support.shared import browser
ModuleNotFoundError: No module named 'selene.support'; 'selene' is not a package
>>> import selene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sugizo/Downloads/jupyter/selene.py", line 1, in <module>
    from selene.support.shared import browser
```

strange things, why python console is accessing selene.py (code above), so tried simplest one
```
cat << EOF > selene.py
import selene
EOF
python selene.py
```

**result** 
nothing (no traceback)

so tried python
```
$ python
Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from selene.support.shared import browser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'selene.support'; 'selene' is not a package
>>> import selene
>>> 
```

same result for selene 2.0.0a34 and 1.0.2

perhaps problem lies in python 3.8.8 or in conda, not sure because no traceback occured

**Comment by aleksandr-kotlyar** [comment] 2021-03-27 21:54
@sugizo I got an idea and think we can try again! 

Could you please
1. update selene version;
2. reproduce the issue;
3. if it still reproduces - do `python -m pip freeze > requirements.txt` ;
4. attach your requirements.txt here in comment.

**Comment by sugizo** [comment] 2021-03-27 23:39
same result tested on 2021-03-28

**step**
```
pip install -U selene --pre
python -m pip freeze > requirements.txt
cat << EOF > selene.py
from selene.support.shared import browser
browser.config.browser_name = 'chrome'
browser.open('https://stifix.pythonanywhere.com/welcome/default/user/login')
browser.element('#auth_user_email').should(be.blank).type('abc')
browser.element('#auth_user_password').should(be.blank).type('cde')
browser.element('#//*[@id="submit_record__row"]/div/input').click()
browser.element('body').should(have.text('Log in') )
browser.quit()
EOF
python selene.py
```

**result**
```
Traceback (most recent call last):
  File "selene.py", line 1, in <module>
    from selene.support.shared import browser
  File "/Users/MacBookPro/Downloads/jupyter/selene.py", line 1, in <module>
    from selene.support.shared import browser
ModuleNotFoundError: No module named 'selene.support'; 'selene' is not a package
```

**attached**
[requirements.txt](https://github.com/yashaka/selene/files/6216598/requirements.txt)

**Comment by aleksandr-kotlyar** [comment] 2021-09-18 08:29
@sugizo hello! Thank you for patience. I have reproduced your issue!
```python3
# selene.py
from selene import have, be
from selene.support.shared import browser
browser.config.browser_name = 'chrome'
browser.open('https://stifix.pythonanywhere.com/welcome/default/user/login')
browser.element('#auth_user_email').should(be.blank).type('abc')
browser.element('#auth_user_password').should(be.blank).type('cde')
browser.element('#//*[@id="submit_record__row"]/div/input').click()
browser.element('body').should(have.text('Log in') )
browser.quit()
```
Have got same error as you did.
```
(.venv) MacBook-Pro-kot:selene kot$ python3 tests/integration/selene.py 
Traceback (most recent call last):
  File "tests/integration/selene.py", line 1, in <module>
    from selene import have, be
  File "/Users/kot/GitHubProjects/selene/tests/integration/selene.py", line 1, in <module>
    from selene import have, be
ImportError: cannot import name 'have' from 'selene' (/Users/kot/GitHubProjects/selene/tests/integration/selene.py)
```

**Reason**: name of your script-file was the same name the library is "selene".

**Solution**: Do not to use "selene" in the name of python files if you want to use selene library.
Try to rename your script-file from "selene.py" to something new, even "try_selene.py". And it will work!

**Closed** 2021-09-18 08:31 UTC
Labels: question, not a bug
