### ISSUE TITLE
Cant perform hover 

### ISSUE THREAD

**Issue by sergsol** [yashaka/selene#183] opened 2018-12-20 12:52 UTC
Trying to use hover on an object throws exception:
selenium.common.exceptions.WebDriverException: Message: unimplemented command: session

Example code:

from selene.api import *
from selenium.common.exceptions import  TimeoutException
config.browser_name = 'chrome'
browser.open_url('https://nplimo.com/')
def to_new_page():
    browser.driver().switch_to.window(browser.driver().window_handles[-1])
s('.footer-logo').scroll_to()
try:
    s('#cn-accept-cookie').click()
except TimeoutException:
    pass
s('#menu-item-1131').click()
s('.footer-logo').scroll_to()
s('.footer-logo').click()
to_new_page()
s('#menu-item-653').hover()
s('#menu-item-121').click()

**Comment by aleksandr-kotlyar** [comment] 2018-12-31 11:30
Hi @yashaka and @sergsol! I wanted to open the same thread about exception thrown by selene `hover()` method. But i have more details, and another exception, than issue-starter.
Here is the issue: **Selene hover() method doesn't work** 

Using:
> selene=1.0.0a13
> selenium=3.141.0
> chrome=71.0.3578.98
> chromedriver=2.45.615291

Executing Code: 
```
from selene import browser
from selene.support.jquery_style_selectors import s

def test_slider():
	browser.open_url("http://your-awesome.url")
        s('[class^="slider_"]').hover()
```

Stacktrace with thrown Exception:
```
test_slider.py::test_slider
Checking for win32 chromedriver:2.45 in cache
Driver found in C:\Users\user\.wdm\chromedriver\2.45\win32/chromedriver.exe
FAILED
test_slider.py:31: in test_slider_has_arrows_on_hover
    s('[class^="slider_"]').hover()
..\..\.venv\lib\site-packages\selene\elements.py:391: in hover
    condition=be.visible)
..\..\.venv\lib\site-packages\selene\elements.py:251: in _execute_on_webelement
    return command(_wait_with_screenshot(self._webdriver, self, condition))
..\..\.venv\lib\site-packages\selene\elements.py:390: in <lambda>
    lambda it: self._actions_chains.move_to_element(it).perform(),
..\..\.venv\lib\site-packages\selenium\webdriver\common\action_chains.py:80: in perform
    self.w3c_actions.perform()
..\..\.venv\lib\site-packages\selenium\webdriver\common\actions\action_builder.py:76: in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
..\..\.venv\lib\site-packages\selene\common\delegation.py:6: in delegator
    return getattr(self.__delegate__, name)(*args, **kwargs)  # pragma: no cover
..\..\.venv\lib\site-packages\selenium\webdriver\remote\webdriver.py:321: in execute
    self.error_handler.check_response(response)
..\..\.venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
E   from invalid argument: 'element' is missing
E     (Session info: chrome=71.0.3578.98)
E     (Driver info: chromedriver=2.45.615291 (ec3682e3c9061c10f26ea9e5cdcf3c53f3f74387),platform=Windows NT 6.1.7601 SP1 x86_64)
```

When i use standart selenium library ActionChains, moving to the same element works fine.
```
from selene import browser
from selene.support.jquery_style_selectors import s
from selenium.webdriver import ActionChains

def some_thing():
	browser.open_url("http://your-awesome.url")
	hover = ActionChains(browser.driver()).move_to_element(s('[class^="slider_"]'))
	hover.perform()
```
Help to localize the cause in selene, and may be someone will make pull-request to fix it's `hover()`
Hope, my temporary solution will be helpful to someone. 
Best regards, Kot

**Comment by akaars** [comment] 2019-01-02 06:17
I found two things:
1) w3c overload in selene.abctypes.webdriver.py:

    @abstractproperty
    def w3c(self):
        # type: () -> bool
        pass

    @abstractmethod
    def w3c(self):
        pass

This caused the incorrect initiation of _driver.w3c value (which is False for the "regular" webdriver, but is  absent in the initiated IWebDriver instance)
As a result "move_to_element" used the if self._driver.w3c and somehow it doesn't work well.

Once the second method commented out the test worked well

**Comment by aleksandr-kotlyar** [comment] 2020-03-07 01:40
Hello here! Good news!

Since PR #184 was cancelled because of new version 2.X.X has been realeased, I returned here with results of issue retest:

I have updated to ver 2.0.0a22 (latest for now) and see that `hover()` works!
```python
from selene import be
from selene.support.shared import browser

def test_slider():
    # issue #183
    browser.open("http://ivi.ru")
    browser.element('[data-ui-id="arthouse"]').should(be.not_.visible)
    browser.element('[data-ui-id="films"]').hover()
    browser.element('[data-ui-id="arthouse"]').should(be.visible)
```
Issue not actual anymore, at least for me. Thanks a lot to @yashaka!

**Closed** 2020-03-07 07:21 UTC
