### ISSUE TITLE
Using element = s(by.xpath(“something”)) in execute_script("some_script", element) causes an error

### ISSUE THREAD

**Issue by byakatat** [yashaka/selene#127] opened 2017-04-26 13:55 UTC
When i put selene element found like that: element = s(by.xpath(“something”)) 
into execute_script("some_script", element) it causes an error:
```python
def scroll(self):
    element = s(by.xpath("//input[@name='groups[214]']/.."))
    driver().execute_script("return arguments[0].scrollIntoView();", element)
```
**error:**
****TypeError**: selene.elements.SeleneElement object at 0x044F1D50 is not JSON serializable**

..........\selene-virt\lib\site-packages\selenium\webdriver\remote\webdriver.py:461: in execute_script
{'script': script, 'args':converted_args})['value']
..........\selene-virt\lib\site-packages\selenium\webdriver\remote\webdriver.py:231: in execute
response = self.command_executor.execute(driver_command, params)
..........\selene-virt\lib\site-packages\selenium\webdriver\remote\remote_connection.py:392: in execute
data = utils.dump_json(params)
..........\selene-virt\lib\site-packages\selenium\webdriver\remote\utils.py:32: in dump_json
return json.dumps(json_struct)
C:\Python35-32\lib\json__init__.py:230: in dumps
return defaultencoder.encode(obj)
C:\Python35-32\lib\json\encoder.py:199: in encode
chunks = self.iterencode(o, oneshot=True)
C:\Python35-32\lib\json\encoder.py:257: in iterencode
return _iterencode(o, 0)

**While this one works fine:**
```python
def scroll(self):
    element = driver().find_element(By.XPATH, "//input[@name='groups[214]']/..")
    driver().execute_script("return arguments[0].scrollIntoView();", element)
```

**Comment by yashaka** [comment] 2017-05-15 20:34
looking into it...

**Comment by yashaka** [comment] 2017-05-15 21:50
So... 

It's complicated... Python can't serialize any custom class...

And that's happened with SeleneElement. It's too smart for Python to serialize it:)

And the problem is that in python there is no way to make "default serialization" for any class object...

You should only by demand specify a custom encoder when trying to encode an object... 

But this "encoding" is a part of Selenium WebDriver that we can't change... 

So, the only workaround that exists is to call SeleneElement#get_actual_webelement() explicitly, like in this test:

```python
def test_can_scroll_to_via_js():
    browser.open_url(start_page)
    logging.warning(browser.driver().current_url)
    browser.driver().set_window_size(300, 400)
    link = s("#invisible_link")
    browser.driver().execute_script("arguments[0].scrollIntoView();", link.get_actual_webelement())
    link.click()
```

https://github.com/yashaka/selene/blob/master/tests/integration/browser_execute_script_test.py

**Comment by yashaka** [comment] 2017-05-15 21:51
Closing this issue...
If have any other ideas to fix this, reopen ;)

**Closed by yashaka** 2017-05-15 21:51 UTC
